# Generated by Django 2.2.3 on 2019-08-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190806_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age_firstentry',
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(default=0.0005263157894736842),
        ),
        migrations.AddField(
            model_name='patient',
            name='district',
            field=models.CharField(default='NA', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='father_name',
            field=models.CharField(default='NA', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='mother_name',
            field=models.CharField(default='NA', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.CharField(default='NA', max_length=80),
            preserve_default=False,
        ),
    ]
