# Generated by Django 2.2.3 on 2019-08-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_patient_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(default='NA'),
            preserve_default=False,
        ),
    ]
