# Generated by Django 2.2.3 on 2019-08-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_patient_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='mobile',
            field=models.IntegerField(default='NA'),
            preserve_default=False,
        ),
    ]
