# Generated by Django 2.2.3 on 2019-08-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_patient_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='mother_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='ID_number',
            field=models.IntegerField(default='NA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='ID_type',
            field=models.CharField(default='NA', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(default='NA', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='pincode',
            field=models.CharField(default='NA', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='district',
            field=models.CharField(max_length=40),
        ),
    ]
